exec-once = hyprpaper
exec-once = swaync
exec-once = systemctl --user start hyprpolkitagent
exec-once = waybar
exec-once = vicinae server
exec-once = swayosd-server
exec-once = hypridle
exec-once = iio-hyprland
exec-once = hyprpm reload
