$mod = SUPER

# power
bind = , XF86PowerOff, exec, vicinae vicinae://open && vicinae vicinae://extensions/vicinae/power/power-off

# launchers
bind = $mod, T, exec, kitty
bind = $mod, P, exec, zen-browser
bind = $mod, O, exec, obsidian
bind = $mod, Space, exec, vicinae toggle

# security
bind = $mod SHIFT, E, exit

# audio and brightness controls
bindl = ,XF86AudioMute, exec, swayosd-client --output-volume mute-toggle
bindel = ,XF86AudioRaiseVolume, exec, swayosd-client --output-volume raise
bindl = ,XF86AudioRaiseVolume, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ 0
bindel = ,XF86AudioLowerVolume, exec, swayosd-client --output-volume lower
bindel = ,XF86MonBrightnessUp, exec, swayosd-client --brightness +5
bindel = ,XF86MonBrightnessDown, exec, swayosd-client --brightness -5

# window management
bind = $mod, Q, killactive
bind = $mod, F, fullscreen, 1
bind = $mod SHIFT, F, fullscreen, 0
bind = $mod SHIFT, T, togglefloating

# focus navigation
bind = $mod, H, movefocus, l
bind = $mod, J, movefocus, d
bind = $mod, K, movefocus, u
bind = $mod, L, movefocus, r

# window movement
bind = $mod SHIFT, H, movewindow, l
bind = $mod SHIFT, J, movewindow, d 
bind = $mod SHIFT, K, movewindow, u
bind = $mod SHIFT, L, movewindow, r

# workspace navigation
bind = $mod, Page_Down, workspace, e+1
bind = $mod, Page_Up, workspace, e-1
bind = $mod, U, workspace, e+1
bind = $mod, I, workspace, e-1

# move to workspace
bind = $mod SHIFT, U, movetoworkspace, e+1
bind = $mod SHIFT, I, movetoworkspace, e-1

# numbered workspaces
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod, 0, workspace, 10

# move to numbered workspaces
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod SHIFT, 7, movetoworkspace, 7
bind = $mod SHIFT, 8, movetoworkspace, 8
bind = $mod SHIFT, 9, movetoworkspace, 9
bind = $mod SHIFT, 0, movetoworkspace, 10

# manual resizing
bind = $mod, minus, resizeactive, -10% 0
bind = $mod, equal, resizeactive, 10% 0
bind = $mod SHIFT, minus, resizeactive, 0 -10%
bind = $mod SHIFT, equal, resizeactive, 0 10%

